# mysql数据库配置
spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wordlastes?useUnicode=true&characterEncoding=utf-8
    username: root
    password: LLsh0718!@#$






