# 服务配置
server:
  port: 8881
# mysql数据库配置
spring:
  # 控制文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: $spring.active$
# mybatis配置
mybatis:
  type-aliases-package: com.bjfu.wordlates.entity
  configuration:
    map-underscore-to-camel-case: true
# 日志配置
logging:
  level:
    root: info
  file:
    path: ./logs
  config: classpath:logback-spring.xml
# 文件上传配置
upload:
  path: ./upload/
# python service配置
python:
  url: http://127.0.0.1:8000/api/




